spring:
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 10s # Tempo de vida dos itens no cache

server:
  port: 8080

logging:
  level:
    org.springframework.cache: INFO
    org.springframework.data.redis: INFO